spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticketflow}
    username: ${DB_USER:ticketflow}
    password: ${DB_PASSWORD:ticketflow}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO

ticketflow:
  seed:
    enabled: false
